# Generated by Django 5.0.1 on 2024-01-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_carthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carthistory',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
